# For the full facil.yaml reference, see:
# https://github.com/cmeeren/Facil/blob/master/facil_reference.yaml

# Allows you to use a $(Variable) in connectionString below (you can use appsettings.json
# and user secrets too, see the full reference linked to above for details)
configs:
  - envVars: ""

rulesets:
  - connectionString: YOUR CONNECTION STRING OR VARIABLE HERE

    # The filename and namespace/module declaration of the generated file. The values
    # below are the defaults. You can remove them if you're happy with them.
    filename: DbGen.fs
    namespaceOrModuleDeclaration: module DbGen

    procedures:

      # Generate wrappers for all stored procedures with the default configuration.
      - include: .*
